(function waitForDependencies(attempt) {
  var dependencies = ["SalaryPrintWorkspaceTemplate", "SalaryPrintMonthPicker", "SalaryPrintDataLoader", "SalaryPrintLayout", "SalaryPrintWorkflow", "SalaryPrintRenderer", "SalaryPrintDocument", "SalaryPrintModelMethodClient", "SalaryPrintRuntimeContext", "SalaryPrintColumnPreferenceStore", "SalaryPrintRequestEnvironment", "SalaryPrintCryptoRuntime", "SalaryPrintSortable"];
  var missing = dependencies.filter(function (name) { return !window[name]; });
  if (missing.length) {
    if (attempt >= 200) { console.error("工资表资源加载失败：" + missing.join(", ")); return; }
    setTimeout(function () { waitForDependencies(attempt + 1); }, 25);
    return;
  }
  (function () {
  SalaryPrintWorkspaceTemplate.mount(document);
  var endpoints={groups:"/xft-gateway/xft-sly/xwapi/salary-calculate/salary-group/sort-query",headers:"/xft-gateway/xft-sly/xwapi/salary-calculate/current-salary/item-header",page:"/xft-gateway/xft-sly/xwapi/salary-query/data-page",key:"/xft-gateway/xft-login-new/xwapi/gateway/security-key/generate"};
  var publicKey="BGMptcE9RGTbVT6NbGLx04ZucPEaRoIOJFM+IrxrwoOdudO7QHgaIX9xq/YcxqWOGGN3WXcvpzoNSZ7ItgerhYU=";
  var state={session:null,groups:[],headers:[],columns:[],rows:[],cancelled:false,document:null,sequence:0,monthKey:null,monthView:null,preferenceStore:null,preferenceRecords:[],sortables:[]};
  function $(id){return document.getElementById(id)} function setStatus(value,error){$("status").textContent=value;$("status").style.color=error?"#a83b32":""}
  function b64bytes(value){return Array.from(Uint8Array.from(atob(value),function(c){return c.charCodeAt(0)}))} function bytes64(value){return btoa(String.fromCharCode.apply(null,value))} function bytes(value){return Array.from(new TextEncoder().encode(value))} function text(value){return new TextDecoder().decode(new Uint8Array(value))}
  function result(operation,key){if(!operation||operation.errorCode!==0)throw new Error(operation&&operation.errorMsg||"加密运行时失败");return operation[key]}
  function usesEncryption(){var tag="";try{tag=window.parent&&window.parent.window&&window.parent.window.envTag||window.parent&&window.parent.envTag||""}catch(_){}return SalaryPrintRequestEnvironment.shouldEncryptRequests(tag)}
  async function initialize(){if(state.session)return state.session;if(!usesEncryption()){state.session={plain:true};return state.session}var cryptoApi=await SalaryPrintCryptoRuntime.ensureCryptoRuntime();var requestTime=Date.now(),randomKey=Array.from(crypto.getRandomValues(new Uint8Array(16))),bootstrap=bytes64(result(cryptoApi.CMBSM2Encrypt(b64bytes(publicKey),bytes(JSON.stringify({randomKey:bytes64(randomKey),timestamp:requestTime}))),"result"));var response=await fetch(endpoints.key,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({data:bootstrap})}),envelope=await response.json();if(envelope.returnCode!=="SUC0000")throw new Error(envelope.errorMsg||"安全密钥协商失败");var keys=JSON.parse(text(result(cryptoApi.CMBSM4DecryptWithCTR(randomKey,b64bytes(envelope.body.data)),"result")));state.session={enc:b64bytes(keys.enckey),sign:b64bytes(keys.sgnkey),version:keys.version,offset:Number(keys.serverTime)-requestTime,crypto:cryptoApi};return state.session}
  async function post(path,payload,menuCode){var session=await initialize(),menu=menuCode||"SAL14000";if(session.plain){var plainResponse=await fetch(path,{method:"POST",credentials:"include",headers:{"content-type":"application/json","xft-menu-code":menu},body:JSON.stringify(payload)}),plainEnvelope=await plainResponse.json();if(plainEnvelope.returnCode!=="SUC0000")throw new Error(plainEnvelope.errorMsg||"工资接口返回失败");return plainEnvelope.body}var cryptoApi=session.crypto,encryptedBody=bytes64(result(cryptoApi.CMBSM4EncryptWithCTR(session.enc,bytes(JSON.stringify(payload))),"result")),timestamp=String(Date.now()+session.offset),nonce=Date.now()+"_"+Math.random().toString(36).slice(2)+"_"+String(state.sequence++%10000).padStart(4,"0"),sign=bytes64(result(cryptoApi.CMBSM2SignWithSM3(session.sign,bytes(nonce+timestamp+encryptedBody+session.version)),"sign"));var response=await fetch(path,{method:"POST",credentials:"include",headers:{"content-type":"application/json","xft-menu-code":menu,"x-xft-request-encrypted":"true","x-xft-nonce":nonce,"x-xft-timestamp":timestamp,"x-xft-key-version":session.version},body:JSON.stringify({encryptedBody:encryptedBody,sign:sign})}),envelope=await response.json();if(envelope.returnCode!=="SUC0000")throw new Error(envelope.errorMsg||"工资接口返回失败");return envelope.body}
  function escapeHtml(value){return String(value===undefined||value===null?"":value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")}
  function destroySortables(){state.sortables.forEach(function(sortable){sortable.destroy()});state.sortables=[]}
  function syncDragOrder(){var keys=[];$("columnEditor").querySelectorAll(".column-group-items .column-item").forEach(function(item){keys.push(item.dataset.key)});state.columns=SalaryPrintLogic.orderColumnsByKeys(state.columns,keys);setStatus("字段顺序已调整，请保存列配置。");renderColumns();prepare()}
  function initializeDragSorting(){var editor=$("columnEditor"),Sortable=window.SalaryPrintSortable;if(!Sortable)return;state.sortables.push(new Sortable(editor,{animation:150,draggable:".column-group",handle:".group-drag",onEnd:syncDragOrder}));editor.querySelectorAll(".column-group-items").forEach(function(list,index){state.sortables.push(new Sortable(list,{group:{name:"salary-print-columns-"+index,pull:false,put:false},animation:150,draggable:".column-item",handle:".column-drag",onEnd:syncDragOrder}))})}
  function renderColumns(){var groups=SalaryPrintLogic.groupColumnsByTopGroup(state.columns),editor=$("columnEditor");destroySortables();editor.innerHTML=groups.map(function(group){return '<section class="column-group" data-group="'+escapeHtml(group.label)+'"><div class="column-group-head"><span><small>一级表头</small><b>'+escapeHtml(group.label)+'</b></span><span class="sort-actions"><button type="button" class="drag-handle group-drag" title="拖拽排序一级表头">&#8942;&#8942;</button><button type="button" class="group-move" data-group="'+escapeHtml(group.label)+'" data-direction="-1" title="一级表头上移">&#8593;</button><button type="button" class="group-move" data-group="'+escapeHtml(group.label)+'" data-direction="1" title="一级表头下移">&#8595;</button></span></div><div class="column-group-items">'+group.columns.map(function(c){var secondGroup=c.secondGroup||c.label,fieldLabel=secondGroup===c.label?"":'<em>字段：'+escapeHtml(c.label)+"</em>";return '<div class="column-item" data-key="'+escapeHtml(c.key)+'"><label class="column-toggle"><input type="checkbox" data-key="'+escapeHtml(c.key)+'" '+(c.printFlag?"checked":"")+'><span><small>二级表头</small><b>'+escapeHtml(secondGroup)+'</b>'+fieldLabel+'</span></label><span class="sort-actions"><button type="button" class="drag-handle column-drag" title="拖拽排序二级表头">&#8942;&#8942;</button><button type="button" class="column-move" data-key="'+escapeHtml(c.key)+'" data-direction="-1" title="二级表头上移">&#8593;</button><button type="button" class="column-move" data-key="'+escapeHtml(c.key)+'" data-direction="1" title="二级表头下移">&#8595;</button></span></div>'}).join("")+"</div></section>"}).join("");editor.querySelectorAll("input").forEach(function(input){input.onchange=function(){state.columns.find(function(c){return c.key===input.dataset.key}).printFlag=input.checked;prepare()}});editor.querySelectorAll(".group-move").forEach(function(button){button.onclick=function(){state.columns=SalaryPrintLogic.moveGroup(state.columns,button.dataset.group,Number(button.dataset.direction));renderColumns();prepare()}});editor.querySelectorAll(".column-move").forEach(function(button){button.onclick=function(){state.columns=SalaryPrintLogic.moveColumnWithinGroup(state.columns,button.dataset.key,Number(button.dataset.direction));renderColumns();prepare()}});initializeDragSorting()}
  function initializePreferenceStore(){var config=window.SalaryPrintModelConfig||{},methods=config.methods||{};if(!config.modelKey||!methods.list||!methods.create||!methods.update)return null;var runtime=SalaryPrintRuntimeContext.createRuntimeContext(),client=SalaryPrintModelMethodClient.createModelMethodClient({baseUrl:runtime.baseUrl,modelKey:config.modelKey,methods:methods}),owner;return SalaryPrintColumnPreferenceStore.createColumnPreferenceStore({client:client,getOwnerUserNo:function(){owner=owner||runtime.getOwnerUserNo();return owner}})}
  async function saveColumns(){if(!state.preferenceStore){setStatus("列配置模型尚未注入，无法保存。",true);return}if(!state.headers.length){setStatus("请先生成工资表后再保存列配置。",true);return}try{await state.preferenceStore.save({salaryGroupId:$("groupSelect").value,salaryCycle:state.monthKey,columns:state.columns,records:state.preferenceRecords});var loaded=await state.preferenceStore.load({salaryGroupId:$("groupSelect").value,salaryCycle:state.monthKey});state.preferenceRecords=loaded.records;setStatus("个人列配置已保存。")}catch(error){setStatus(error.message||"保存列配置失败",true)}}
  function render(){if(!state.document)return;var group=state.groups.find(function(item){return item.salaryGroupId===$("groupSelect").value});var columns=state.columns.filter(function(c){return c.printFlag}),groupName=group?group.salaryGroupName:"—";$("printPages").innerHTML=SalaryPrintRenderer.renderPrintPages({pages:state.document.pages,columns:columns,totals:SalaryPrintLogic.calculateTotals(state.rows,columns),title:state.monthKey.slice(0,4)+"年"+Number(state.monthKey.slice(4))+"月"+groupName+"工资表",totalRows:state.rows.length});document.documentElement.style.setProperty("--print-size",state.document.fit.paper);document.documentElement.style.setProperty("--print-font",state.document.fit.fontPt+"pt");$("printSummary").textContent="共 "+state.rows.length+" 条，预计 "+state.document.pages.length+" 页，"+state.document.fit.paper+"，字号 "+state.document.fit.fontPt+"pt。";$("printButton").disabled=false}
  async function prepare(){if(!state.rows.length)return;var result=await SalaryPrintWorkflow.preparePrintDocument({paper:$("paperSelect").value,columns:state.columns,loader:{loadPage:async function(){return {records:state.rows,total:state.rows.length}}}});if(!result.canPrint){$("printSummary").textContent=result.fit.status==="suggest-a3"?"当前 A4 需低于 6.5pt；请切换 A3 横向或调整列。":"当前 A3 仍超宽，请调整可选列。";$("printButton").disabled=true;return}state.document=result;state.document.pages.forEach(function(page){page.rows.forEach(function(row,index){row._sequence=state.rows.indexOf(row)+1})});render()}
  async function query(){var groupId=$("groupSelect").value,cycle=state.monthKey;try{state.cancelled=false;$("cancelLoadButton").hidden=false;$("progressBar").style.width="0%";setStatus("正在读取实时表头和全部工资数据…");var response=await Promise.all([post(endpoints.headers,{salaryGroupId:groupId,batchNumber:"",queryType:"1",itemHeaderType:"other"},"SAL20000"),state.preferenceStore?state.preferenceStore.load({salaryGroupId:groupId,salaryCycle:cycle}):Promise.resolve({records:[],preferences:[]})]),headers=SalaryPrintLogic.flattenCategoryHeaders(response[0]),preferences=response[1];var loaded=await SalaryPrintDataLoader.loadAllSalaryRows({isCancelled:function(){return state.cancelled},onProgress:function(p){$("loadProgress").textContent="已加载 "+p.loaded+" / "+p.total+" 条";$("progressBar").style.width=(p.total?Math.min(100,p.loaded/p.total*100):0)+"%"},loadPage:async function(page){var body=await post(endpoints.page,{current:page.current,size:page.size,records:[{salaryGroupId:groupId,salaryPeriodBegin:cycle,salaryPeriodEnd:cycle,editFlag:true}]});var data=body.salaryDetailDataPages||body;return {records:data.records||[],total:data.total||data.totalCount||0}}});state.headers=headers;state.preferenceRecords=preferences.records;state.columns=SalaryPrintLogic.buildColumns(headers,preferences.preferences);state.rows=SalaryPrintLogic.normalizeRows(loaded.records,state.columns);renderColumns();await prepare();setStatus("工资表已生成。")}catch(error){setStatus(error.message||"查询失败",true)}finally{$("cancelLoadButton").hidden=true}}
  function renderMonthPicker(){var picker=SalaryPrintMonthPicker,nowKey=picker.toMonthKey(new Date()),start=state.monthView.slice(0,4)+"01";$("monthPickerTitle").textContent=start.slice(0,4)+" 年";$("monthPickerButton").textContent=picker.formatMonthLabel(state.monthKey);$("monthGrid").innerHTML=Array.from({length:12},function(_,index){var key=start.slice(0,4)+String(index+1).padStart(2,"0"),disabled=!picker.canSelectMonth(key,nowKey);return '<button type="button" data-month="'+key+'" '+(disabled?"disabled":"")+' class="'+(key===state.monthKey?"selected":"")+'">'+String(index+1).padStart(2,"0")+'月</button>'}).join("");$("monthGrid").querySelectorAll("button").forEach(function(button){button.onclick=function(){if(button.disabled)return;state.monthKey=button.dataset.month;$("monthPickerDialog").hidden=true;renderMonthPicker()}})}
  function printOnlyPages(){var pages=$("printPages");if(!pages||!pages.innerHTML.trim()){setStatus("请先生成工资表后再打印。",true);return}var popup=window.open("", "salary-print-document");if(!popup){setStatus("浏览器拦截了打印窗口，请允许弹窗后重试。",true);return}var css=document.querySelector('link[rel="stylesheet"]');popup.opener=null;popup.document.open();popup.document.write(SalaryPrintDocument.createPrintDocument({title:"工资表打印预览",cssHref:css&&css.href,pagesHtml:pages.innerHTML}));popup.document.close()}
  async function start(){state.monthKey=SalaryPrintMonthPicker.toMonthKey(new Date());state.monthView=state.monthKey;state.preferenceStore=initializePreferenceStore();renderMonthPicker();$("monthPickerButton").onclick=function(){$("monthPickerDialog").hidden=!$("monthPickerDialog").hidden};$("monthPrevious").onclick=function(){state.monthView=SalaryPrintMonthPicker.shiftMonth(state.monthView,-12);renderMonthPicker()};$("monthNext").onclick=function(){var next=SalaryPrintMonthPicker.shiftMonth(state.monthView,12),now=SalaryPrintMonthPicker.toMonthKey(new Date());if(next<=now){state.monthView=next;renderMonthPicker()}};$("queryButton").onclick=query;$("cancelLoadButton").onclick=function(){state.cancelled=true};$("paperSelect").onchange=prepare;$("printButton").onclick=printOnlyPages;var saveButton=$("saveColumns");if(saveButton)saveButton.onclick=saveColumns;$("resetColumns").onclick=function(){state.columns=SalaryPrintLogic.buildColumns(state.headers,[]);state.preferenceRecords=[];renderColumns();prepare()};try{state.groups=await post(endpoints.groups,{authorityCode:"SASALSHW"});$("groupSelect").innerHTML=state.groups.map(function(g){return '<option value="'+g.salaryGroupId+'">'+g.salaryGroupName+'</option>'}).join("");setStatus("请选择薪资组和所属期后查询。") }catch(error){setStatus(error.message||"初始化失败",true)}} start();
  })();
})(0);
