(function () {
  SalaryPrintWorkspaceTemplate.mount(document);
  var endpoints={groups:"/xft-gateway/xft-sly/xwapi/salary-calculate/salary-group/sort-query",headers:"/xft-gateway/xft-sly/xwapi/salary-query/header-query",page:"/xft-gateway/xft-sly/xwapi/salary-query/data-page",key:"/xft-gateway/xft-login-new/xwapi/gateway/security-key/generate"};
  var publicKey="BGMptcE9RGTbVT6NbGLx04ZucPEaRoIOJFM+IrxrwoOdudO7QHgaIX9xq/YcxqWOGGN3WXcvpzoNSZ7ItgerhYU=";
  var state={session:null,groups:[],headers:[],columns:[],rows:[],cancelled:false,document:null,sequence:0};
  function $(id){return document.getElementById(id)} function setStatus(value,error){$("status").textContent=value;$("status").style.color=error?"#a83b32":""}
  function b64bytes(value){return Array.from(Uint8Array.from(atob(value),function(c){return c.charCodeAt(0)}))} function bytes64(value){return btoa(String.fromCharCode.apply(null,value))} function bytes(value){return Array.from(new TextEncoder().encode(value))} function text(value){return new TextDecoder().decode(new Uint8Array(value))}
  function result(operation,key){if(!operation||operation.errorCode!==0)throw new Error(operation&&operation.errorMsg||"加密运行时失败");return operation[key]}
  async function initialize(){if(state.session)return state.session;var cryptoApi=window.cmbSoftAlgrithm||(window.parent&&window.parent.cmbSoftAlgrithm);if(!cryptoApi)throw new Error("父页面未加载 cmbSoftAlgrithm");var requestTime=Date.now(),randomKey=Array.from(crypto.getRandomValues(new Uint8Array(16))),bootstrap=bytes64(result(cryptoApi.CMBSM2Encrypt(b64bytes(publicKey),bytes(JSON.stringify({randomKey:bytes64(randomKey),timestamp:requestTime}))),"result"));var response=await fetch(endpoints.key,{method:"POST",credentials:"include",headers:{"content-type":"application/json"},body:JSON.stringify({data:bootstrap})}),envelope=await response.json();if(envelope.returnCode!=="SUC0000")throw new Error(envelope.errorMsg||"安全密钥协商失败");var keys=JSON.parse(text(result(cryptoApi.CMBSM4DecryptWithCTR(randomKey,b64bytes(envelope.body.data)),"result")));state.session={enc:b64bytes(keys.enckey),sign:b64bytes(keys.sgnkey),version:keys.version,offset:Number(keys.serverTime)-requestTime};return state.session}
  async function post(path,payload){var session=await initialize(),cryptoApi=window.cmbSoftAlgrithm||(window.parent&&window.parent.cmbSoftAlgrithm),encryptedBody=bytes64(result(cryptoApi.CMBSM4EncryptWithCTR(session.enc,bytes(JSON.stringify(payload))),"result")),timestamp=String(Date.now()+session.offset),nonce=Date.now()+"_"+Math.random().toString(36).slice(2)+"_"+String(state.sequence++%10000).padStart(4,"0"),sign=bytes64(result(cryptoApi.CMBSM2SignWithSM3(session.sign,bytes(nonce+timestamp+encryptedBody+session.version)),"sign"));var response=await fetch(path,{method:"POST",credentials:"include",headers:{"content-type":"application/json","xft-menu-code":"SAL14000","x-xft-request-encrypted":"true","x-xft-nonce":nonce,"x-xft-timestamp":timestamp,"x-xft-key-version":session.version},body:JSON.stringify({encryptedBody:encryptedBody,sign:sign})}),envelope=await response.json();if(envelope.returnCode!=="SUC0000")throw new Error(envelope.errorMsg||"工资接口返回失败");return envelope.body}
  function renderColumns(){ $("columnEditor").innerHTML=state.columns.map(function(c){return '<label class="column-item"><input type="checkbox" data-key="'+c.key+'" '+(c.printFlag?"checked":"")+'><span>'+c.label+'<small>'+c.group+'</small></span></label>'}).join("");$("columnEditor").querySelectorAll("input").forEach(function(input){input.onchange=function(){state.columns.find(function(c){return c.key===input.dataset.key}).printFlag=input.checked;prepare()}})}
  function render(){if(!state.document)return;var group=state.groups.find(function(item){return item.salaryGroupId===$("groupSelect").value});var columns=state.columns.filter(function(c){return c.printFlag});$("printPages").innerHTML=SalaryPrintRenderer.renderPrintPages({pages:state.document.pages,columns:columns,totals:SalaryPrintLogic.calculateTotals(state.rows,columns),title:$("cycleInput").value.slice(0,4)+" 年 "+Number($("cycleInput").value.slice(4))+" 月工资表",groupName:"薪资组："+(group?group.salaryGroupName:"—"),cycleName:"薪资所属期："+$("cycleInput").value,totalRows:state.rows.length});document.documentElement.style.setProperty("--print-size",state.document.fit.paper);document.documentElement.style.setProperty("--print-font",state.document.fit.fontPt+"pt");$("printSummary").textContent="共 "+state.rows.length+" 条，预计 "+state.document.pages.length+" 页，"+state.document.fit.paper+"，字号 "+state.document.fit.fontPt+"pt。";$("printButton").disabled=false}
  async function prepare(){if(!state.rows.length)return;var result=await SalaryPrintWorkflow.preparePrintDocument({paper:$("paperSelect").value,columns:state.columns,loader:{loadPage:async function(){return {records:state.rows,total:state.rows.length}}}});if(!result.canPrint){$("printSummary").textContent=result.fit.status==="suggest-a3"?"当前 A4 需低于 6.5pt；请切换 A3 横向或调整列。":"当前 A3 仍超宽，请调整可选列。";$("printButton").disabled=true;return}state.document=result;state.document.pages.forEach(function(page){page.rows.forEach(function(row,index){row._sequence=state.rows.indexOf(row)+1})});render()}
  async function query(){var groupId=$("groupSelect").value,cycle=$("cycleInput").value.trim();if(!/^\d{6}$/.test(cycle)){setStatus("薪资所属期请输入 6 位 YYYYMM。",true);return}try{state.cancelled=false;$("cancelLoadButton").hidden=false;setStatus("正在读取实时表头和全部工资数据…");var headers=await post(endpoints.headers,{salaryGroupId:groupId,salaryPeriodBegin:cycle,salaryPeriodEnd:cycle});var loaded=await SalaryPrintDataLoader.loadAllSalaryRows({isCancelled:function(){return state.cancelled},onProgress:function(p){$("loadProgress").textContent="已加载 "+p.loaded+" / "+p.total+" 条"},loadPage:async function(page){var body=await post(endpoints.page,{current:page.current,size:page.size,records:[{salaryGroupId:groupId,salaryPeriodBegin:cycle,salaryPeriodEnd:cycle,editFlag:true}]});var data=body.salaryDetailDataPages||body;return {records:data.records||[],total:data.total||data.totalCount||0}}});state.headers=headers;state.columns=SalaryPrintLogic.buildColumns(headers,[]);state.rows=SalaryPrintLogic.normalizeRows(loaded.records,state.columns);renderColumns();await prepare();setStatus("工资表已生成。")}catch(error){setStatus(error.message||"查询失败",true)}finally{$("cancelLoadButton").hidden=true}}
  async function start(){var d=new Date();$("cycleInput").value=d.getFullYear()+String(d.getMonth()+1).padStart(2,"0");$("queryButton").onclick=query;$("cancelLoadButton").onclick=function(){state.cancelled=true};$("paperSelect").onchange=prepare;$("printButton").onclick=function(){window.print()};$("resetColumns").onclick=function(){state.columns=SalaryPrintLogic.buildColumns(state.headers,[]);renderColumns();prepare()};try{state.groups=await post(endpoints.groups,{authorityCode:"SASALSHW"});$("groupSelect").innerHTML=state.groups.map(function(g){return '<option value="'+g.salaryGroupId+'">'+g.salaryGroupName+'</option>'}).join("");setStatus("请选择薪资组和所属期后查询。") }catch(error){setStatus(error.message||"初始化失败",true)}} start();
})();
